networks:
  clients-network:
    name: "clients-network"
services:
  db:
    image: postgres:15
    container_name: db_clients
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - clients-network

  app:
    container_name: api_clients
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/mydb?sslmode=disable"
    ports:
      - "8080:8080"
    links:
      - db
    networks:
      - clients-network
    env_file:
      - .env

volumes:
  pgdata:
